package com.mycompany.uno;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chief
 */
public class HideCardsWin extends javax.swing.JFrame {
    private Timer timer;
    private int secondsLeft;
    private LiveGameWin lgw;
    /**
     * Creates new form HideCardsWin
     */
    public HideCardsWin(String nextPlayer, LiveGameWin lgw) {
        initComponents();
        this.secondsLeft = 15;
        initializeTimer();
        lblNextPlayer.setText(String.valueOf(nextPlayer));
        this.lgw = lgw;
    }
    
    private void initializeTimer(){
        //Initilize the timer
        //src: https://www.youtube.com/watch?v=978GXYn-Kn4&t=169s
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                countDown();
            }
        });
        timer.start();
    }
    
    private void countDown() {
        secondsLeft -= 1;
        lblTimeLeft.setText(String.valueOf(secondsLeft));
        if(secondsLeft <= 3){
            lblTimeLeft.setForeground(Color.red);
        }
        if(secondsLeft == 0){
           timer.stop();
           this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHideCards = new javax.swing.JPanel();
        lblGiveComputerTo = new javax.swing.JLabel();
        lblNextPlayer = new javax.swing.JLabel();
        lblTimeLeft = new javax.swing.JLabel();
        lblContinue = new javax.swing.JButton();
        lblNote = new javax.swing.JLabel();
        lblStarryImageHolder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlHideCards.setBackground(new java.awt.Color(153, 255, 153));
        pnlHideCards.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGiveComputerTo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblGiveComputerTo.setForeground(new java.awt.Color(255, 255, 255));
        lblGiveComputerTo.setText("Give the computer to:");
        pnlHideCards.add(lblGiveComputerTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblNextPlayer.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblNextPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblNextPlayer.setText("Name");
        pnlHideCards.add(lblNextPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lblTimeLeft.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 100)); // NOI18N
        lblTimeLeft.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeLeft.setText("15");
        pnlHideCards.add(lblTimeLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 168, -1));

        lblContinue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblContinue.setText("Continue");
        lblContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContinueActionPerformed(evt);
            }
        });
        pnlHideCards.add(lblContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 129, 64));

        lblNote.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblNote.setForeground(new java.awt.Color(255, 255, 255));
        lblNote.setText("(Click \"Continue\" when Ready)");
        pnlHideCards.add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        lblStarryImageHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starry_background2.png"))); // NOI18N
        lblStarryImageHolder.setText("jLabel4");
        pnlHideCards.add(lblStarryImageHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHideCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHideCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContinueActionPerformed
        // TODO add your handling code here:
        this.dispose();
        lgw.checkPlayerMoves();
    }//GEN-LAST:event_lblContinueActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HideCardsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HideCardsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HideCardsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HideCardsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HideCardsWin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lblContinue;
    private javax.swing.JLabel lblGiveComputerTo;
    private javax.swing.JLabel lblNextPlayer;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblStarryImageHolder;
    private javax.swing.JLabel lblTimeLeft;
    private javax.swing.JPanel pnlHideCards;
    // End of variables declaration//GEN-END:variables
}
