/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

/**
 *
 * @author chief
 */
public class InstructionsWin extends javax.swing.JFrame {

    /**
     * Creates new form InstructionsWin
     */
    public InstructionsWin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInstructions = new javax.swing.JPanel();
        lblHowToPlay = new javax.swing.JLabel();
        lblObjective = new javax.swing.JLabel();
        btn3Players = new javax.swing.JButton();
        btn2Players = new javax.swing.JButton();
        btn4Players = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        lblDescription2 = new javax.swing.JLabel();
        lblDescription4 = new javax.swing.JLabel();
        lblDescription3 = new javax.swing.JLabel();
        lblPurpleImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInstructions.setBackground(new java.awt.Color(153, 255, 153));
        pnlInstructions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHowToPlay.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lblHowToPlay.setForeground(new java.awt.Color(204, 255, 255));
        lblHowToPlay.setText("How to play:");
        pnlInstructions.add(lblHowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 20, -1, -1));

        lblObjective.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lblObjective.setForeground(new java.awt.Color(153, 255, 255));
        lblObjective.setText("Objective:");
        pnlInstructions.add(lblObjective, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 93, -1, -1));

        btn3Players.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btn3Players.setText("3 Players");
        btn3Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3PlayersActionPerformed(evt);
            }
        });
        pnlInstructions.add(btn3Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 554, 229, 68));

        btn2Players.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btn2Players.setText("2 Players");
        btn2Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2PlayersActionPerformed(evt);
            }
        });
        pnlInstructions.add(btn2Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 554, 229, 68));

        btn4Players.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btn4Players.setText("4 Players");
        btn4Players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4PlayersActionPerformed(evt);
            }
        });
        pnlInstructions.add(btn4Players, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 554, 229, 68));

        lblQuestion.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(204, 255, 255));
        lblQuestion.setText("How many players do you have?");
        pnlInstructions.add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 493, -1, -1));

        lblDescription1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDescription1.setForeground(new java.awt.Color(204, 255, 255));
        lblDescription1.setText("The objective of your game is to get rid of all your cards");
        pnlInstructions.add(lblDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblDescription2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDescription2.setForeground(new java.awt.Color(204, 255, 255));
        lblDescription2.setText("Play any card that matches either the color or number of the current card in the discard pile");
        pnlInstructions.add(lblDescription2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblDescription4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDescription4.setForeground(new java.awt.Color(204, 255, 255));
        lblDescription4.setText("If you have no legal moves when its your turn , draw one card and move on to the next player (automatic)");
        pnlInstructions.add(lblDescription4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lblDescription3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDescription3.setForeground(new java.awt.Color(204, 255, 255));
        lblDescription3.setText("Once you have played a card, a seperate screen will pop up hiding the next players cards, hand the computer to the next player");
        pnlInstructions.add(lblDescription3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        lblPurpleImage.setForeground(new java.awt.Color(204, 255, 255));
        lblPurpleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purple_background.png"))); // NOI18N
        lblPurpleImage.setText("jLabel11");
        pnlInstructions.add(lblPurpleImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4PlayersActionPerformed
        // TODO add your handling code here:
        PlayerInfoWin win = new PlayerInfoWin(4);
        win.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn4PlayersActionPerformed

    private void btn3PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3PlayersActionPerformed
        // TODO add your handling code here:
        PlayerInfoWin win = new PlayerInfoWin(3);
        win.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn3PlayersActionPerformed

    private void btn2PlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2PlayersActionPerformed
        // TODO add your handling code here:
        PlayerInfoWin win = new PlayerInfoWin(2);
        win.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn2PlayersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructionsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructionsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructionsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructionsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructionsWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2Players;
    private javax.swing.JButton btn3Players;
    private javax.swing.JButton btn4Players;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblDescription3;
    private javax.swing.JLabel lblDescription4;
    private javax.swing.JLabel lblHowToPlay;
    private javax.swing.JLabel lblObjective;
    private javax.swing.JLabel lblPurpleImage;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JPanel pnlInstructions;
    // End of variables declaration//GEN-END:variables
}
