/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uno;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 *
 * @author chief
 */
public class UnoMain extends javax.swing.JFrame {

    /**
     * Creates new form UnoDesign
     */
    public UnoMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeScreen3 = new javax.swing.JPanel();
        lblUnoMainMenu3 = new javax.swing.JLabel();
        lblContinueMainMenu3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblCredits3 = new javax.swing.JLabel();
        lblVisual5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomeScreen3.setBackground(new java.awt.Color(153, 255, 153));
        HomeScreen3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUnoMainMenu3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 68)); // NOI18N
        lblUnoMainMenu3.setText("------------------- UNO ---------------------");
        lblUnoMainMenu3.setToolTipText("");
        HomeScreen3.add(lblUnoMainMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1200, -1));

        lblContinueMainMenu3.setBackground(new java.awt.Color(0, 255, 204));
        lblContinueMainMenu3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lblContinueMainMenu3.setText("Continue");
        lblContinueMainMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContinueMainMenuActionPerformed(evt);
            }
        });
        HomeScreen3.add(lblContinueMainMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 440, 100));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton4.setText("Quit Program");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        HomeScreen3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 180, 50));

        lblCredits3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblCredits3.setText("created by: Ethan Makabali     email: emakabali@mail.endicott.edu");
        HomeScreen3.add(lblCredits3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 82, 840, -1));

        lblVisual5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblVisual5.setText("Visual Programming II");
        HomeScreen3.add(lblVisual5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unobackground.png"))); // NOI18N
        HomeScreen3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 1420, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeScreen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeScreen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void lblContinueMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContinueMainMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InstructionsWin win = new InstructionsWin();
        win.setVisible(true);
    }//GEN-LAST:event_lblContinueMainMenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want quit?",
                "Exit?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomeScreen3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lblContinueMainMenu3;
    private javax.swing.JLabel lblCredits3;
    private javax.swing.JLabel lblUnoMainMenu3;
    private javax.swing.JLabel lblVisual5;
    // End of variables declaration//GEN-END:variables
}
